### PR TITLE
Add IP addresses for rfa2-vm and rfa3-vm

### PR DESCRIPTION
**Pull request by ekyono**
Please review and pull this config update.

### CODE REVIEW

**Comment by himorin** [comment]
add other interfaces of rfa[23] also.

**Comment by ekyono** [comment]
iDRAC? 
- If yes, it will be on Subaru LAN outside of PFS LAN.
- If no, no other ether connection exists on this server. I thought...

If I misunderstand shimono-san's comment, please let me know.

**Comment by ekyono** [comment]
Updated iDRAC mac and IP addresses. Also, modified nfs server related aliases.

**Comment by ekyono** [comment]
Shimono-san,

Could you give us a little bit more explanation why our machine needs to be other than rfa2-vm and what issue we will have if we do so?
In my understanding, the one you mentioned has different domain name at IPMU which is separated environment from subaru summit one.
I think we can give different hostname for the one called rfa2-vm at IPMU if it comes to subaru.

Eiji

**Pull request merged**
